name: Update Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update followers list & Blogs list
        run: |
          cd scripts && npm install && ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} npm start
      - name: Commit changes
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_USERNAME }}"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Updated README.md"
      - name: Pull changes
        run: git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
